source 'https://rubygems.org'

gem 'activerecord'
gem 'cgi'
gem 'dotenv'
gem 'dotiw'
gem 'erubis'
gem 'flag_shih_tzu'
gem 'honeybadger'
gem 'mysql2'
gem 'nokogiri'
gem 'puma'
gem 'pusher'
gem 'rake'
gem 'redcarpet'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'with_advisory_lock'
